import { jsPDF } from "jspdf";
import { Invoice, OrgProfile } from "@/store/useAppStore";

const hexToRgb = (hex: string): [number, number, number] => {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? [
    parseInt(result[1], 16),
    parseInt(result[2], 16),
    parseInt(result[3], 16)
  ] : [34, 197, 94]; // fallback to emerald-500
};

export function generateInvoicePdf(invoice: Invoice, orgProfile: OrgProfile) {
  const doc = new jsPDF();
  
  // Organization Header
  doc.setFontSize(24);
  doc.setTextColor(...hexToRgb(orgProfile.primaryColor || '#10b981'));
  doc.text(orgProfile.name, 20, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`${orgProfile.sector} | INVOICE`, 20, 32);

  // Invoice Details right aligned
  doc.setFontSize(20);
  doc.setTextColor(50);
  doc.text("INVOICE", 190, 25, { align: "right" });
  
  doc.setFontSize(10);
  doc.text(`Invoice #: ${invoice.id}`, 190, 32, { align: "right" });
  doc.text(`Date: ${invoice.date}`, 190, 38, { align: "right" });
  doc.text(`Due Date: ${invoice.dueDate}`, 190, 44, { align: "right" });
  
  // Line separator
  doc.setDrawColor(200);
  doc.line(20, 50, 190, 50);

  // Bill To
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", 20, 65);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(50);
  doc.text(invoice.client, 20, 72);
  if (invoice.clientAddress) doc.text(invoice.clientAddress, 20, 78);
  if (invoice.clientEmail) doc.text(invoice.clientEmail, 20, 84);
  if (invoice.clientPhone) doc.text(invoice.clientPhone, 20, 90);

  // Table Header
  const tableTop = 110;
  doc.setFillColor(248, 250, 252);
  doc.rect(20, tableTop, 170, 10, "FD");
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text("Description", 25, tableTop + 7);
  doc.text("Qty", 120, tableTop + 7);
  doc.text("Unit Price", 140, tableTop + 7);
  doc.text("Amount", 170, tableTop + 7);
  
  // Table Rows
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50);
  
  let currentY = tableTop + 17;
  
  invoice.lineItems?.forEach((item) => {
    const amount = item.qty * item.unitPrice;
    doc.text(item.description, 25, currentY);
    doc.text(item.qty.toString(), 120, currentY);
    doc.text(`KES ${item.unitPrice.toLocaleString()}`, 140, currentY);
    doc.text(`KES ${amount.toLocaleString()}`, 170, currentY);
    currentY += 10;
  });

  // Subtotals and Grand Total
  currentY += 5;
  doc.setDrawColor(200);
  doc.line(110, currentY, 190, currentY);
  
  currentY += 7;
  const subtotal = invoice.lineItems?.reduce((sum, item) => sum + (item.qty * item.unitPrice), 0) || 0;
  doc.text("Subtotal:", 140, currentY);
  doc.text(`KES ${subtotal.toLocaleString()}`, 170, currentY);
  
  currentY += 7;
  const tax = subtotal * ((invoice.taxRate || 0) / 100);
  doc.text(`Tax (${invoice.taxRate}%):`, 140, currentY);
  doc.text(`KES ${tax.toLocaleString()}`, 170, currentY);
  
  currentY += 5;
  doc.line(110, currentY, 190, currentY);
  
  currentY += 7;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text("Total Due:", 140, currentY);
  doc.text(`KES ${invoice.amount}`, 170, currentY);

  // Notes
  doc.setFont("helvetica", "normal");
  if (invoice.notes) {
    currentY += 20;
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Notes / Terms:", 20, currentY);
    doc.setTextColor(50);
    const splitNotes = doc.splitTextToSize(invoice.notes, 170);
    doc.text(splitNotes, 20, currentY + 6);
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by LedgerLink", 105, 280, { align: "center" });

  // Save PDF
  doc.save(`${invoice.id}.pdf`);
}
