import { jsPDF } from "jspdf";
import { OrgProfile } from "@/store/useAppStore";
import { PayrollBreakdown } from "./calculatePayroll";

const hexToRgb = (hex: string): [number, number, number] => {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? [
    parseInt(result[1], 16),
    parseInt(result[2], 16),
    parseInt(result[3], 16)
  ] : [34, 197, 94]; // fallback to emerald-500
};

export function generatePayslipPDF(
  employee: { id: string; name: string; role: string; gross: number },
  deductions: PayrollBreakdown,
  orgProfile: OrgProfile,
  period: string
) {
  const doc = new jsPDF();
  
  // Organization Header
  doc.setFontSize(22);
  doc.setTextColor(...hexToRgb(orgProfile.primaryColor || '#10b981'));
  doc.text(orgProfile.name, 20, 20);
  
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`${orgProfile.sector} | Payslip for ${period}`, 20, 30);
  
  // Line separator
  doc.setDrawColor(200);
  doc.line(20, 35, 190, 35);

  // Employee Details
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Employee Details", 20, 50);
  
  doc.setFontSize(11);
  doc.setTextColor(50);
  doc.text(`Name: ${employee.name}`, 20, 60);
  doc.text(`ID: ${employee.id}`, 20, 70);
  doc.text(`Role: ${employee.role}`, 20, 80);

  // Earnings & Deductions Header
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Earnings & Deductions", 20, 100);
  
  // Table Box
  doc.setDrawColor(200);
  doc.setFillColor(248, 250, 252); // slate-50
  doc.rect(20, 105, 170, 70, "FD");

  doc.setFontSize(11);
  doc.setTextColor(50);

  // Rows
  const startY = 115;
  const lineSpacing = 10;
  
  doc.text("Gross Salary:", 25, startY);
  doc.text(`KES ${employee.gross.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 150, startY);

  doc.text("Taxable Pay:", 25, startY + lineSpacing);
  doc.text(`KES ${deductions.taxablePay.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 150, startY + lineSpacing);

  doc.text("PAYE (Tax):", 25, startY + lineSpacing * 2);
  doc.text(`- KES ${deductions.paye.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 150, startY + lineSpacing * 2);

  doc.text("Personal Relief:", 25, startY + lineSpacing * 3);
  doc.text(`+ KES ${deductions.personalRelief.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 150, startY + lineSpacing * 3);

  doc.text("NSSF:", 25, startY + lineSpacing * 4);
  doc.text(`- KES ${deductions.nssf.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 150, startY + lineSpacing * 4);

  doc.text("SHIF:", 25, startY + lineSpacing * 5);
  doc.text(`- KES ${deductions.shif.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 150, startY + lineSpacing * 5);

  doc.text("AHL:", 25, startY + lineSpacing * 6);
  doc.text(`- KES ${deductions.ahl.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 150, startY + lineSpacing * 6);

  // Net Pay Line
  doc.setDrawColor(200);
  doc.line(25, startY + lineSpacing * 7 - 3, 185, startY + lineSpacing * 7 - 3);

  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text("Net Pay:", 25, startY + lineSpacing * 8);
  doc.text(`KES ${deductions.net.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 150, startY + lineSpacing * 8);
  doc.setFont("helvetica", "normal");

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by LedgerLink", 105, 280, { align: "center" });

  // Save the PDF
  doc.save(`Payslip-${employee.id}-${period}.pdf`);
}
